// resgister a node
// errors from axios just status code
// - register for orcheseterator  information to store ? endpoint name , address - domain name cdndameon-my.com , identity - did, stats - throughput + upspeed + downspeed , ip addresses -

// generate a did store their privkey - these tthings are autogenerated

// Multiple - register for hub / coordinator node  , ipfs peer id , hive account optional , storage space , estimated server throuhput
// each standard endpoint can use multiple hub nodes , hardcoded or variable

// what do we mean by they can register with your node
